# Arrays


## ¿Qué son las dimensiones en arrays?



El concepto de "dimensiones" en arrays se refiere a **cuántos índices necesitas para acceder a un elemento**, no al tamaño del array:

- **1 dimensión (vector)**: Solo necesitas 1 índice → `array[i]`
- **2 dimensiones (matriz)**: Necesitas 2 índices → `array[fila, columna]`  
- **3 dimensiones (tensor)**: Necesitas 3 índices → `array[profundidad, fila, columna]`

## Arrays de 1 dimensión (vector)

### np.array

In [11]:
# Array de 1 dimensión
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
print("Array de 1 dimensión:")
print(array_1d)

Array de 1 dimensión:
[1 2 3 4 5]


### np.arange

In [12]:
# np.arange es una función muy útil de NumPy que crea arrays con valores espaciados uniformemente
# dentro de un rango específico. Es similar a la función range() de Python, pero devuelve un array de NumPy.

# Sintaxis: np.arange(start, stop, step)
# - start: valor inicial (incluido)
# - stop: valor final (no incluido)
# - step: incremento entre valores (por defecto es 1)

print("Ejemplos de np.arange:")

# Crear array del 0 al 9
array_0_9 = np.arange(10)
print(f"np.arange(10): {array_0_9}")

# Crear array del 2 al 9
array_2_9 = np.arange(2, 10)
print(f"np.arange(2, 10): {array_2_9}")

# Crear array del 0 al 20 con paso de 2
array_pares = np.arange(0, 21, 2)
print(f"np.arange(0, 21, 2): {array_pares}")

# También funciona con números decimales
array_decimal = np.arange(0, 1, 0.2)
print(f"np.arange(0, 1, 0.2): {array_decimal}")

Ejemplos de np.arange:
np.arange(10): [0 1 2 3 4 5 6 7 8 9]
np.arange(2, 10): [2 3 4 5 6 7 8 9]
np.arange(0, 21, 2): [ 0  2  4  6  8 10 12 14 16 18 20]
np.arange(0, 1, 0.2): [0.  0.2 0.4 0.6 0.8]


### np.linspace

In [13]:
# np.linspace es otra función fundamental de NumPy que crea arrays con un número específico
# de elementos espaciados uniformemente entre dos valores (incluidos ambos extremos).
# Es muy útil cuando necesitas un número exacto de puntos en un rango.

# Sintaxis: np.linspace(start, stop, num)
# - start: valor inicial (incluido)
# - stop: valor final (incluido)
# - num: número de elementos a generar (por defecto es 50)

print("Ejemplos de np.linspace:")

# Crear 5 puntos entre 0 y 10
array_linspace_5 = np.linspace(0, 10, 5)
print(f"np.linspace(0, 10, 5): {array_linspace_5}")

# Crear 11 puntos entre 0 y 1
array_linspace_11 = np.linspace(0, 1, 11)
print(f"np.linspace(0, 1, 11): {array_linspace_11}")

# Diferencia clave con arange:
# - arange: especificas el PASO entre elementos
# - linspace: especificas el NÚMERO TOTAL de elementos

print("\nComparación arange vs linspace:")
print(f"arange(0, 11, 2): {np.arange(0, 11, 2)}")
print(f"linspace(0, 10, 6): {np.linspace(0, 10, 6)}")

Ejemplos de np.linspace:
np.linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
np.linspace(0, 1, 11): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

Comparación arange vs linspace:
arange(0, 11, 2): [ 0  2  4  6  8 10]
linspace(0, 10, 6): [ 0.  2.  4.  6.  8. 10.]


## Arrays de 2 dimensiones (matriz)

### np.array

In [14]:
# Array de 2 dimensiones (matriz)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array de 2 dimensiones:")
print(array_2d)
print(f"Forma del array: {array_2d.shape}")
print(f"Número de dimensiones: {array_2d.ndim}")

Array de 2 dimensiones:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma del array: (3, 3)
Número de dimensiones: 2


### np.eye

In [15]:
# np.eye crea una matriz identidad (matriz cuadrada con 1s en la diagonal principal y 0s en el resto)
# Es muy útil en álgebra lineal y operaciones matriciales

# Sintaxis: np.eye(N, M=None, k=0)
# - N: número de filas
# - M: número de columnas (si no se especifica, será igual a N)
# - k: índice de la diagonal (0 = diagonal principal, >0 = diagonal superior, <0 = diagonal inferior)

print("Ejemplos de np.eye:")

# Matriz identidad 3x3
matriz_identidad_3x3 = np.eye(3)
print("np.eye(3) - Matriz identidad 3x3:")
print(matriz_identidad_3x3)

# Matriz identidad 4x4
matriz_identidad_4x4 = np.eye(4)
print("\nnp.eye(4) - Matriz identidad 4x4:")
print(matriz_identidad_4x4)

# Matriz rectangular 3x5
matriz_rectangular = np.eye(3, 5)
print("\nnp.eye(3, 5) - Matriz rectangular 3x5:")
print(matriz_rectangular)

# Diagonal superior (k=1)
matriz_diagonal_superior = np.eye(4, k=1)
print("\nnp.eye(4, k=1) - Diagonal superior:")
print(matriz_diagonal_superior)

# Diagonal inferior (k=-1)
matriz_diagonal_inferior = np.eye(4, k=-1)
print("\nnp.eye(4, k=-1) - Diagonal inferior:")
print(matriz_diagonal_inferior)

Ejemplos de np.eye:
np.eye(3) - Matriz identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.eye(4) - Matriz identidad 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.eye(3, 5) - Matriz rectangular 3x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

np.eye(4, k=1) - Diagonal superior:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

np.eye(4, k=-1) - Diagonal inferior:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### np.diag

In [16]:
# np.diag es una función versátil que puede extraer la diagonal de una matriz 
# o crear una matriz diagonal a partir de un array 1D

# Sintaxis: np.diag(v, k=0)
# - v: array de entrada (1D para crear matriz diagonal, 2D para extraer diagonal)
# - k: índice de la diagonal (0 = diagonal principal, >0 = diagonal superior, <0 = diagonal inferior)

print("Ejemplos de np.diag:")

# Crear matriz diagonal a partir de un array 1D
diagonal_values = np.array([1, 5, 9, 3])
matriz_diagonal = np.diag(diagonal_values)
print("np.diag([1, 5, 9, 3]) - Crear matriz diagonal:")
print(matriz_diagonal)

# Extraer diagonal principal de una matriz existente
diagonal_extraida = np.diag(array_2d)
print(f"\nnp.diag(array_2d) - Extraer diagonal principal: {diagonal_extraida}")

# Crear matriz con diagonal superior (k=1)
matriz_diag_superior = np.diag([2, 4, 6], k=1)
print("\nnp.diag([2, 4, 6], k=1) - Diagonal superior:")
print(matriz_diag_superior)

# Crear matriz con diagonal inferior (k=-1)
matriz_diag_inferior = np.diag([1, 3, 5], k=-1)
print("\nnp.diag([1, 3, 5], k=-1) - Diagonal inferior:")
print(matriz_diag_inferior)

# Extraer diagonal superior de matriz existente
diagonal_superior_extraida = np.diag(array_2d, k=1)
print(f"\nnp.diag(array_2d, k=1) - Extraer diagonal superior: {diagonal_superior_extraida}")

Ejemplos de np.diag:
np.diag([1, 5, 9, 3]) - Crear matriz diagonal:
[[1 0 0 0]
 [0 5 0 0]
 [0 0 9 0]
 [0 0 0 3]]

np.diag(array_2d) - Extraer diagonal principal: [1 5 9]

np.diag([2, 4, 6], k=1) - Diagonal superior:
[[0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]
 [0 0 0 0]]

np.diag([1, 3, 5], k=-1) - Diagonal inferior:
[[0 0 0 0]
 [1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]]

np.diag(array_2d, k=1) - Extraer diagonal superior: [2 6]


### np.vender

In [17]:
# np.vander crea una matriz de Vandermonde a partir de un array 1D
# Una matriz de Vandermonde es útil en interpolación polinómica y álgebra lineal

# Sintaxis: np.vander(x, N=None, increasing=False)
# - x: array de entrada 1D
# - N: número de columnas (por defecto es len(x))
# - increasing: si True, las potencias van de menor a mayor (por defecto False)

print("Ejemplos de np.vander:")

# Matriz de Vandermonde básica
array_simple = np.array([1, 2, 3])
matriz_vander = np.vander(array_simple)
print("np.vander([1, 2, 3]) - Matriz de Vandermonde:")
print(matriz_vander)
print("Cada fila contiene: [x^2, x^1, x^0]")

# Con número específico de columnas
matriz_vander_4 = np.vander(array_simple, N=4)
print("\nnp.vander([1, 2, 3], N=4) - 4 columnas:")
print(matriz_vander_4)
print("Cada fila contiene: [x^3, x^2, x^1, x^0]")

# Con potencias crecientes
matriz_vander_creciente = np.vander(array_simple, increasing=True)
print("\nnp.vander([1, 2, 3], increasing=True):")
print(matriz_vander_creciente)
print("Cada fila contiene: [x^0, x^1, x^2]")

# Ejemplo con array existente
matriz_vander_existente = np.vander(array_1d, N=3)
print(f"\nnp.vander({array_1d}, N=3):")
print(matriz_vander_existente)

Ejemplos de np.vander:
np.vander([1, 2, 3]) - Matriz de Vandermonde:
[[1 1 1]
 [4 2 1]
 [9 3 1]]
Cada fila contiene: [x^2, x^1, x^0]

np.vander([1, 2, 3], N=4) - 4 columnas:
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]
Cada fila contiene: [x^3, x^2, x^1, x^0]

np.vander([1, 2, 3], increasing=True):
[[1 1 1]
 [1 2 4]
 [1 3 9]]
Cada fila contiene: [x^0, x^1, x^2]

np.vander([1 2 3 4 5], N=3):
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


## general ndarray creation functions

In [18]:
# np.zeros - crea array lleno de ceros
print("np.zeros(5) - Array 1D de ceros:")
zeros_1d = np.zeros(5)
print(zeros_1d)

print("\nnp.zeros((3, 4)) - Array 2D de ceros:")
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

np.zeros(5) - Array 1D de ceros:
[0. 0. 0. 0. 0.]

np.zeros((3, 4)) - Array 2D de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# np.ones - crea array lleno de unos
print("\nnp.ones(4) - Array 1D de unos:")
ones_1d = np.ones(4)
print(ones_1d)

print("\nnp.ones((2, 3)) - Array 2D de unos:")
ones_2d = np.ones((2, 3))
print(ones_2d)


np.ones(4) - Array 1D de unos:
[1. 1. 1. 1.]

np.ones((2, 3)) - Array 2D de unos:
[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# np.full - crea array lleno de un valor específico
print("\nnp.full(6, 7) - Array lleno de 7s:")
full_array = np.full(6, 7)
print(full_array)

print("\nnp.full((2, 4), 3.5) - Array 2D lleno de 3.5s:")
full_2d = np.full((2, 4), 3.5)
print(full_2d)


np.full(6, 7) - Array lleno de 7s:
[7 7 7 7 7 7]

np.full((2, 4), 3.5) - Array 2D lleno de 3.5s:
[[3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5]]


In [21]:
# np.empty - crea array sin inicializar (valores aleatorios)
print("\nnp.empty(4) - Array sin inicializar:")
empty_array = np.empty(4)
print(empty_array)


np.empty(4) - Array sin inicializar:
[1. 1. 1. 1.]


In [22]:
# np.zeros_like, np.ones_like, np.full_like - crean arrays con la misma forma que otro
# Asumiendo que estos arrays ya existen de un código anterior
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2], [3, 4]])
matriz_identidad_3x3 = np.identity(3)


print(f"\nnp.zeros_like(array_2d) - Ceros con forma {array_2d.shape}:")
zeros_like = np.zeros_like(array_2d)
print(zeros_like)

print(f"\nnp.ones_like(array_1d) - Unos con forma {array_1d.shape}:")
ones_like = np.ones_like(array_1d)
print(ones_like)

print(f"\nnp.full_like(matriz_identidad_3x3, 8) - Lleno de 8s con forma {matriz_identidad_3x3.shape}:")
full_like = np.full_like(matriz_identidad_3x3, 8)
print(full_like)


np.zeros_like(array_2d) - Ceros con forma (2, 2):
[[0 0]
 [0 0]]

np.ones_like(array_1d) - Unos con forma (3,):
[1 1 1]

np.full_like(matriz_identidad_3x3, 8) - Lleno de 8s con forma (3, 3):
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [23]:
# np.random - genera arrays con números aleatorios
print("\nFunciones de np.random:")

# Números aleatorios uniformes entre 0 y 1
print("np.random.rand(5) - Números aleatorios uniformes:")
random_array = np.random.rand(5)
print(random_array)

# Números aleatorios uniformes en forma 2D
print("\nnp.random.rand(3, 3) - Array 2D aleatorio:")
random_2d = np.random.rand(3, 3)
print(random_2d)

# Números aleatorios con distribución normal (media=0, desviación=1)
print("\nnp.random.randn(4) - Distribución normal:")
random_normal = np.random.randn(4)
print(random_normal)

# Enteros aleatorios en un rango
print("\nnp.random.randint(1, 10, 6) - Enteros aleatorios entre 1 y 9:")
random_int = np.random.randint(1, 10, 6)
print(random_int)


Funciones de np.random:
np.random.rand(5) - Números aleatorios uniformes:
[0.62096914 0.61707062 0.28460065 0.77107119 0.32641708]

np.random.rand(3, 3) - Array 2D aleatorio:
[[0.12722766 0.4087257  0.8332461 ]
 [0.4228229  0.77203486 0.56538686]
 [0.41548559 0.0413742  0.91757204]]

np.random.randn(4) - Distribución normal:
[-0.70507272  0.73975214  0.31085456  0.68203003]

np.random.randint(1, 10, 6) - Enteros aleatorios entre 1 y 9:
[6 9 6 5 8 4]


In [24]:
# np.indices - genera arrays de índices
print("\nFunciones de np.indices:")

# Indices para una grilla 2D
print("np.indices((3, 4)) - Índices para grilla 3x4:")
indices_2d = np.indices((3, 4))
print("Índices de filas:")
print(indices_2d[0])
print("Índices de columnas:")
print(indices_2d[1])

# Indices para una grilla 3D
print("\nnp.indices((2, 3, 2)) - Índices para grilla 2x3x2:")
indices_3d = np.indices((2, 3, 2))
print("Forma del resultado:", indices_3d.shape)
print("Índices de la primera dimensión:")
print(indices_3d[0])


Funciones de np.indices:
np.indices((3, 4)) - Índices para grilla 3x4:
Índices de filas:
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
Índices de columnas:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

np.indices((2, 3, 2)) - Índices para grilla 2x3x2:
Forma del resultado: (3, 2, 3, 2)
Índices de la primera dimensión:
[[[0 0]
  [0 0]
  [0 0]]

 [[1 1]
  [1 1]
  [1 1]]]
